import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.arcadecabinet.aethelgard',
  appName: 'Aethelgard',
  webDir: 'dist',
  server: {
    androidScheme: 'https',
    // M_AUDIT2.SEC2.4 — unique hostname so the WebView storage partition
    // (localStorage / IndexedDB / Preferences on web fallback) is scoped
    // to THIS app's origin. Capacitor default 'localhost' would share
    // origin with any other Capacitor app on the device.
    hostname: 'aethelgard.local',
  },
  android: {
    // M_AUDIT2.SEC2.3 — explicit security defaults for release builds.
    // Capacitor sets sane defaults but pinning them here makes the
    // policy version-controlled + diff-reviewable; a future Capacitor
    // upgrade that flips a default doesn't silently weaken the app.
    webContentsDebuggingEnabled: false,
    allowMixedContent: false,
    captureInput: true,
  },
  // M_EXPANSION.S.64 — iOS configuration. The ios/ Xcode scaffold
  // is generated by `pnpm cap add ios` (one-shot developer action;
  // needs Xcode installed locally). This config block is the
  // runtime policy the scaffold reads.
  ios: {
    // Match the Android-side defaults: production builds disable
    // WebView debugging. The iOS WKWebView is sandboxed per app
    // by default so no Android-equivalent of captureInput is needed.
    webContentsDebuggingEnabled: false,
    // 'automatic' lets WKWebView handle safe-area insets so HUD
    // pills + EndTurnButton don't collide with the Dynamic Island
    // or home-bar on newer iPhones.
    contentInset: 'automatic',
  },
};

export default config;
